Repository status-im/react-native-desktop, pull requests merged in 2018-06, with the labels that each got.

#228 refs #225 - Use QtWebKit on Windows with MinGW
  CMakeLists.txt
  ReactQt/application/src/CMakeLists.txt
  ReactQt/runtime/src/CMakeLists.txt
  ReactQt/runtime/src/componentmanagers/webviewmanager.cpp
  ReactQt/runtime/src/qml/ReactQtWebKitWebView.qml
  ReactQt/runtime/src/react_resources.qrc
  local-cli/generator-desktop/templates/CMakeLists.txt
Labels: feature

#247 Doc about Yoga layout engine used in react-native-desktop
  README.md
  docs/ReactQt/YogaLayoutEngine.md
Labels: docs

#272 Support Qt components linkage defined in native modules; Resolve file…
  ReactQt/runtime/src/CMakeLists.txt
Labels: bug, feature

#275 CMake command to copy single file instead directory
  Examples/2048/CMakeLists.txt
  Examples/Movies/CMakeLists.txt
  Examples/UIExplorer/CMakeLists.txt
  RNTester/CMakeLists.txt
Labels: bug
